#!/usr/bin/env node

const program = require('commander');
const verify = require('../checkValidity.js')

program
    .option('-S, --source_rpc <required>', 'Source RPC')
    .option('-s, --source_contract_address <required>', 'Source contract address')
    .option('-T, --target_rpc <required>', 'Target RPC')
    .option('-t, --target_contract_address <required>', 'Target contract address')
    .parse(process.argv);

verify.isStateEqual(
    program.source_rpc,
    program.source_contract_address,
    program.target_rpc,
    program.target_contract_address
).then(result => {
    if(result)
        console.log('The state of both smart contracts is equal');
    else
        console.log('The state of both smart contract IS NOT EQUAL');
}).catch((reason) => {
    console.log(`Something went wrong: ${reason}`);
}).then(() => {
    process.exit();
});