#!/usr/bin/env node

const program = require('commander');
const sharedAttributes = require('./index-shared-attributes');
const contractHelper = require('../contractHelper');
const Web3 = require("web3");

sharedAttributes(program);

program
    .parse(process.argv);

// check if addresses have the right format.
const addressFormat = new RegExp(/0x[\d\w]+/);
if (!addressFormat.test(program.contract)) {
    console.log('Contract address is not in the correct format. Please use "0x..." as a format.');
    process.exit();
}

const web3 = new Web3(program.source);

const node = program.parity ? 'parity' : 'geth';

contractHelper.getState(
    web3.utils.toChecksumAddress(program.contract),
    web3,
    {
        deployment_tx_hash: program.deployment_hash ? program.deployment_hash : undefined,
        csv_path: program.file ? program.file : undefined,
        node: node,
        fat_db: program.fatDb ? program.fatDb : false,
        max_depth: program.recursion ? program.recursion : -1,
        block_number: program.block_number ? Web3.utils.toHex(program.block_number) : 'latest',
        targetFile: program.output ? program.output : undefined
    }
).then(() => {
    process.exit();
});