#!/usr/bin/env node

module.exports = (program) => {
    program
        .option('-s, --source <required>', 'Source RPC')
        .option('-c, --contract <required>', 'Source contract address')
        .option('-d, --deployment_hash [optional]', 'Hash of the deployment transaction')
        .option('-x, --transaction-input [optional]', 'Source file (csv) containing TXs to be replayed')
        .option('-p, --parity', 'Use parity compatible replay commands instead of geth')
        .option('-q, --fat-db [result_limit (int)]', 'Use key retrieval from parity\'s fat_db feature. Provide result limit for retrieved storage keys. Default: 100')
        .option('-o, --output [optional]', 'Save key pairs in json file')
};
