#!/usr/bin/env node

const program = require('commander');
const sharedAttributes = require('./index-shared-attributes');
const redeployFunc = require('../redeployContract');

sharedAttributes(program);


program
    .option('-t, --target <required>', 'Target RPC')
    .option('-a, --address <required>', 'Address to use on target blockchain (unlocked)')
    .parse(process.argv);

const node = program.parity ? 'parity' : 'geth';

redeployFunc.portContract(
    program.contract,
    program.source,
    program.target,
    program.address,
    {
        deployment_tx_hash: program.deployment_hash ? program.deployment_hash : undefined,
        csv_path: program.file ? program.file : undefined,
        node: node,
        fat_db: program.fatDb ? program.fatDb : false,
        targetFile: program.output ? program.output : undefined
    }
);
